package RemotelyInvokableHospitalApp;


/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public interface RemotelyInvokableHospitalOperations 
{
  String addAppointment (String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType, int capacity);
  String removeAppointment (String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType);
  String listAppointmentAvailability (RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType);
  String bookAppointment (String patientId, String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType);
  String getAppointmentSchedule (String patientId);
  String cancelAppointment (String patientId, String appointmentId);
  String swapAppointment (String patientId, String oldAppointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType oldAppointmentType, String newAppointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType newAppointmentType);
} // interface RemotelyInvokableHospitalOperations
