package RemotelyInvokableHospitalApp;

/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public final class RemotelyInvokableHospitalHolder implements org.omg.CORBA.portable.Streamable
{
  public RemotelyInvokableHospitalApp.RemotelyInvokableHospital value = null;

  public RemotelyInvokableHospitalHolder ()
  {
  }

  public RemotelyInvokableHospitalHolder (RemotelyInvokableHospitalApp.RemotelyInvokableHospital initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RemotelyInvokableHospitalApp.RemotelyInvokableHospitalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RemotelyInvokableHospitalApp.RemotelyInvokableHospitalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RemotelyInvokableHospitalApp.RemotelyInvokableHospitalHelper.type ();
  }

}
