package RemotelyInvokableHospitalApp;


/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

abstract public class RemotelyInvokableHospitalHelper
{
  private static String  _id = "IDL:RemotelyInvokableHospitalApp/RemotelyInvokableHospital:1.0";

  public static void insert (org.omg.CORBA.Any a, RemotelyInvokableHospitalApp.RemotelyInvokableHospital that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospital extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RemotelyInvokableHospitalApp.RemotelyInvokableHospitalHelper.id (), "RemotelyInvokableHospital");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospital read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemotelyInvokableHospitalStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RemotelyInvokableHospitalApp.RemotelyInvokableHospital value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospital narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotelyInvokableHospitalApp.RemotelyInvokableHospital)
      return (RemotelyInvokableHospitalApp.RemotelyInvokableHospital)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotelyInvokableHospitalApp._RemotelyInvokableHospitalStub stub = new RemotelyInvokableHospitalApp._RemotelyInvokableHospitalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospital unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotelyInvokableHospitalApp.RemotelyInvokableHospital)
      return (RemotelyInvokableHospitalApp.RemotelyInvokableHospital)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotelyInvokableHospitalApp._RemotelyInvokableHospitalStub stub = new RemotelyInvokableHospitalApp._RemotelyInvokableHospitalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
