package corbasystem;


/**
* corbasystem/IFrontEndServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Friday, November 1, 2019 8:44:19 o'clock AM EDT
*/

public interface IFrontEndServerOperations 
{
  String initiateServer (String city);
  String requestHandler (String userId, String command, String parameters);
} // interface IFrontEndServerOperations
