package corbasystem;


/**
* corbasystem/IFrontEndServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Friday, November 1, 2019 8:44:19 o'clock AM EDT
*/

public interface IFrontEndServer extends IFrontEndServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IFrontEndServer
