package corbasystem;


/**
* corbasystem/IFrontEndServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Sunday, November 24, 2019 10:52:32 o'clock PM EST
*/

public interface IFrontEndServer extends IFrontEndServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IFrontEndServer
