package corbasystem;

/**
* corbasystem/IFrontEndServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Sunday, November 24, 2019 9:41:38 o'clock PM EST
*/

public final class IFrontEndServerHolder implements org.omg.CORBA.portable.Streamable
{
  public corbasystem.IFrontEndServer value = null;

  public IFrontEndServerHolder ()
  {
  }

  public IFrontEndServerHolder (corbasystem.IFrontEndServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbasystem.IFrontEndServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbasystem.IFrontEndServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbasystem.IFrontEndServerHelper.type ();
  }

}
