package ReplicaManagers.Dong.corbasystem_RM;


/**
* corbasystem/IServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Saturday, October 12, 2019 9:30:42 o'clock PM EDT
*/

public interface IServer extends IServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IServer
