package ReplicaManagers.Dong.corbasystem_RM;


/**
* corbasystem/IServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Saturday, October 12, 2019 9:30:42 o'clock PM EDT
*/

public interface IServerOperations 
{
  String initiateServer(String city);
  String addAppointment(String appointmentID, String appointmentType, String capacity);
  String removeAppointment(String appointmentID, String appointmentType);
  String listAppointmentAvailability(String appointmentType);
  String bookAppointment(String patientID, String appointmentID, String appointmentType);
  String getAppointmentSchedule(String patientID);
  String cancelAppointment(String patientID, String appointmentID);
  String swapAppointment(String patientID, String oldAppointmentID, String oldAppointmentType,
                         String newAppointmentID, String newAppointmentType);
} // interface IServerOperations
