package ReplicaManagers.Dong.corbasystem_RM;


/**
* corbasystem/IServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Saturday, October 12, 2019 9:30:42 o'clock PM EDT
*/

public abstract class IServerPOA extends org.omg.PortableServer.Servant
 implements ReplicaManagers.Dong.corbasystem_RM.IServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("initiateServer", new Integer (0));
    _methods.put ("addAppointment", new Integer (1));
    _methods.put ("removeAppointment", new Integer (2));
    _methods.put ("listAppointmentAvailability", new Integer (3));
    _methods.put ("bookAppointment", new Integer (4));
    _methods.put ("getAppointmentSchedule", new Integer (5));
    _methods.put ("cancelAppointment", new Integer (6));
    _methods.put ("swapAppointment", new Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corbasystem/IServer/initiateServer
       {
         String city = in.read_string ();
         String $result = null;
         $result = this.initiateServer (city);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corbasystem/IServer/addAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String capacity = in.read_string ();
         String $result = null;
         $result = this.addAppointment (appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // corbasystem/IServer/removeAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // corbasystem/IServer/listAppointmentAvailability
       {
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // corbasystem/IServer/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // corbasystem/IServer/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // corbasystem/IServer/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // corbasystem/IServer/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbasystem/IServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IServer _this() 
  {
    return IServerHelper.narrow(
    super._this_object());
  }

  public IServer _this(org.omg.CORBA.ORB orb) 
  {
    return IServerHelper.narrow(
    super._this_object(orb));
  }


} // class IServerPOA
