package ReplicaManagers.Dong.corbasystem_RM;

/**
* corbasystem/IServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Saturday, October 12, 2019 9:30:42 o'clock PM EDT
*/

public final class IServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ReplicaManagers.Dong.corbasystem_RM.IServer value = null;

  public IServerHolder ()
  {
  }

  public IServerHolder (ReplicaManagers.Dong.corbasystem_RM.IServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReplicaManagers.Dong.corbasystem_RM.IServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReplicaManagers.Dong.corbasystem_RM.IServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReplicaManagers.Dong.corbasystem_RM.IServerHelper.type ();
  }

}
