package ReplicaManagers.Dong.corbasystem_RM;


/**
* corbasystem/IServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbasystem.idl
* Saturday, October 12, 2019 9:30:42 o'clock PM EDT
*/

abstract public class IServerHelper
{
  private static String  _id = "IDL:corbasystem/IServer:1.0";

  public static void insert (org.omg.CORBA.Any a, ReplicaManagers.Dong.corbasystem_RM.IServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ReplicaManagers.Dong.corbasystem_RM.IServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (id(), "IServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ReplicaManagers.Dong.corbasystem_RM.IServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ReplicaManagers.Dong.corbasystem_RM.IServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ReplicaManagers.Dong.corbasystem_RM.IServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReplicaManagers.Dong.corbasystem_RM.IServer)
      return (ReplicaManagers.Dong.corbasystem_RM.IServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReplicaManagers.Dong.corbasystem_RM._IServerStub stub = new ReplicaManagers.Dong.corbasystem_RM._IServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ReplicaManagers.Dong.corbasystem_RM.IServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReplicaManagers.Dong.corbasystem_RM.IServer)
      return (ReplicaManagers.Dong.corbasystem_RM.IServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReplicaManagers.Dong.corbasystem_RM._IServerStub stub = new ReplicaManagers.Dong.corbasystem_RM._IServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
