package RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage;


/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalPackage/AppointmentTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

abstract public class AppointmentTypeHelper
{
  private static String  _id = "IDL:RemotelyInvokableHospitalApp/RemotelyInvokableHospital/AppointmentType:1.0";

  public static void insert (org.omg.CORBA.Any a, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.id (), "AppointmentType", new String[] { "Physician", "Surgeon", "Dental"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType read (org.omg.CORBA.portable.InputStream istream)
  {
    return RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType value)
  {
    ostream.write_long (value.value ());
  }

}
