package RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage;

/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalPackage/AppointmentTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public final class AppointmentTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType value = null;

  public AppointmentTypeHolder ()
  {
  }

  public AppointmentTypeHolder (RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.type ();
  }

}
