package RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage;


/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospitalPackage/AppointmentType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public class AppointmentType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType[] __array = new RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType [__size];

  public static final int _Physician = 0;
  public static final RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType Physician = new RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType(_Physician);
  public static final int _Surgeon = 1;
  public static final RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType Surgeon = new RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType(_Surgeon);
  public static final int _Dental = 2;
  public static final RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType Dental = new RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType(_Dental);

  public int value ()
  {
    return __value;
  }

  public static RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AppointmentType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AppointmentType
