package RemotelyInvokableHospitalApp;


/**
* RemotelyInvokableHospitalApp/_RemotelyInvokableHospitalStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public class _RemotelyInvokableHospitalStub extends org.omg.CORBA.portable.ObjectImpl implements RemotelyInvokableHospitalApp.RemotelyInvokableHospital
{

  public String addAppointment (String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType, int capacity)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addAppointment", true);
                $out.write_string (appointmentId);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, appointmentType);
                $out.write_long (capacity);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addAppointment (appointmentId, appointmentType, capacity        );
            } finally {
                _releaseReply ($in);
            }
  } // addAppointment

  public String removeAppointment (String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeAppointment", true);
                $out.write_string (appointmentId);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, appointmentType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return removeAppointment (appointmentId, appointmentType        );
            } finally {
                _releaseReply ($in);
            }
  } // removeAppointment

  public String listAppointmentAvailability (RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listAppointmentAvailability", true);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, appointmentType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listAppointmentAvailability (appointmentType        );
            } finally {
                _releaseReply ($in);
            }
  } // listAppointmentAvailability

  public String bookAppointment (String patientId, String appointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType appointmentType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bookAppointment", true);
                $out.write_string (patientId);
                $out.write_string (appointmentId);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, appointmentType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return bookAppointment (patientId, appointmentId, appointmentType        );
            } finally {
                _releaseReply ($in);
            }
  } // bookAppointment

  public String getAppointmentSchedule (String patientId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAppointmentSchedule", true);
                $out.write_string (patientId);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAppointmentSchedule (patientId        );
            } finally {
                _releaseReply ($in);
            }
  } // getAppointmentSchedule

  public String cancelAppointment (String patientId, String appointmentId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelAppointment", true);
                $out.write_string (patientId);
                $out.write_string (appointmentId);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cancelAppointment (patientId, appointmentId        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelAppointment

  public String swapAppointment (String patientId, String oldAppointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType oldAppointmentType, String newAppointmentId, RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentType newAppointmentType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("swapAppointment", true);
                $out.write_string (patientId);
                $out.write_string (oldAppointmentId);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, oldAppointmentType);
                $out.write_string (newAppointmentId);
                RemotelyInvokableHospitalApp.RemotelyInvokableHospitalPackage.AppointmentTypeHelper.write ($out, newAppointmentType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return swapAppointment (patientId, oldAppointmentId, oldAppointmentType, newAppointmentId, newAppointmentType        );
            } finally {
                _releaseReply ($in);
            }
  } // swapAppointment

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RemotelyInvokableHospitalApp/RemotelyInvokableHospital:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RemotelyInvokableHospitalStub
