package RemotelyInvokableHospitalApp;


/**
* RemotelyInvokableHospitalApp/RemotelyInvokableHospital.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemotelyInvokableHospitalCorba.idl
* Tuesday, October 8, 2019 6:04:55 o'clock PM EDT
*/

public interface RemotelyInvokableHospital extends RemotelyInvokableHospitalApp.RemotelyInvokableHospitalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface RemotelyInvokableHospital
