package DhmsApp;

/**
* DhmsApp/DhmsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Friday, November 22, 2019 1:09:15 o'clock PM EST
*/

public final class DhmsHolder implements org.omg.CORBA.portable.Streamable
{
  public DhmsApp.Dhms value = null;

  public DhmsHolder ()
  {
  }

  public DhmsHolder (DhmsApp.Dhms initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DhmsApp.DhmsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DhmsApp.DhmsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DhmsApp.DhmsHelper.type ();
  }

}
