package DhmsApp;


/**
* DhmsApp/Dhms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Friday, November 22, 2019 1:09:15 o'clock PM EST
*/

public interface Dhms extends DhmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dhms
