package DhmsApp;


/**
* DhmsApp/DhmsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Friday, November 22, 2019 1:09:15 o'clock PM EST
*/

public abstract class DhmsPOA extends org.omg.PortableServer.Servant
 implements DhmsApp.DhmsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
    _methods.put ("bookAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("cancelAppointment", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("loginAdmin", new java.lang.Integer (7));
    _methods.put ("logoutAdmin", new java.lang.Integer (8));
    _methods.put ("loginPatient", new java.lang.Integer (9));
    _methods.put ("logoutPatient", new java.lang.Integer (10));
    _methods.put ("validateAppointmentID", new java.lang.Integer (11));
    _methods.put ("validateAppointmentType", new java.lang.Integer (12));
    _methods.put ("showAppointmentRecords", new java.lang.Integer (13));
    _methods.put ("showPatientRecords", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DhmsApp/Dhms/addAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addAppointment (appointmentID, appointmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DhmsApp/Dhms/removeAppointment
       {
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DhmsApp/Dhms/listAppointmentAvailability
       {
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DhmsApp/Dhms/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DhmsApp/Dhms/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DhmsApp/Dhms/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DhmsApp/Dhms/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DhmsApp/Dhms/loginAdmin
       {
         String adminID = in.read_string ();
         int $result = (int)0;
         $result = this.loginAdmin (adminID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // DhmsApp/Dhms/logoutAdmin
       {
         String adminID = in.read_string ();
         int $result = (int)0;
         $result = this.logoutAdmin (adminID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // DhmsApp/Dhms/loginPatient
       {
         String patientID = in.read_string ();
         int $result = (int)0;
         $result = this.loginPatient (patientID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 10:  // DhmsApp/Dhms/logoutPatient
       {
         String patientID = in.read_string ();
         int $result = (int)0;
         $result = this.logoutPatient (patientID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // DhmsApp/Dhms/validateAppointmentID
       {
         String id = in.read_string ();
         boolean $result = false;
         $result = this.validateAppointmentID (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 12:  // DhmsApp/Dhms/validateAppointmentType
       {
         String type = in.read_string ();
         boolean $result = false;
         $result = this.validateAppointmentType (type);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 13:  // DhmsApp/Dhms/showAppointmentRecords
       {
         String $result = null;
         $result = this.showAppointmentRecords ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 14:  // DhmsApp/Dhms/showPatientRecords
       {
         String $result = null;
         $result = this.showPatientRecords ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DhmsApp/Dhms:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dhms _this() 
  {
    return DhmsHelper.narrow(
    super._this_object());
  }

  public Dhms _this(org.omg.CORBA.ORB orb) 
  {
    return DhmsHelper.narrow(
    super._this_object(orb));
  }


} // class DhmsPOA
