package DhmsApp;


/**
* DhmsApp/Dhms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Monday, November 11, 2019 6:01:56 o'clock PM EST
*/

public interface Dhms extends DhmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dhms
