package DhmsApp;


/**
* DhmsApp/hashMapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

public final class hashMapHolder implements org.omg.CORBA.portable.Streamable
{
  public DhmsApp.HashMapOuter value[] = null;

  public hashMapHolder ()
  {
  }

  public hashMapHolder (DhmsApp.HashMapOuter[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DhmsApp.hashMapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DhmsApp.hashMapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DhmsApp.hashMapHelper.type ();
  }

}
