package DhmsApp;

/**
* DhmsApp/HashMapOuterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

public final class HashMapOuterHolder implements org.omg.CORBA.portable.Streamable
{
  public DhmsApp.HashMapOuter value = null;

  public HashMapOuterHolder ()
  {
  }

  public HashMapOuterHolder (DhmsApp.HashMapOuter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DhmsApp.HashMapOuterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DhmsApp.HashMapOuterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DhmsApp.HashMapOuterHelper.type ();
  }

}
