package DhmsApp;


/**
* DhmsApp/hashMapHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

abstract public class hashMapHelper
{
  private static String  _id = "IDL:DhmsApp/hashMap:1.0";

  public static void insert (org.omg.CORBA.Any a, DhmsApp.HashMapOuter[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DhmsApp.HashMapOuter[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DhmsApp.HashMapOuterHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DhmsApp.hashMapHelper.id (), "hashMap", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DhmsApp.HashMapOuter[] read (org.omg.CORBA.portable.InputStream istream)
  {
    DhmsApp.HashMapOuter value[] = null;
    int _len0 = istream.read_long ();
    value = new DhmsApp.HashMapOuter[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = DhmsApp.HashMapOuterHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DhmsApp.HashMapOuter[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      DhmsApp.HashMapOuterHelper.write (ostream, value[_i0]);
  }

}
