package DhmsApp;


/**
* DhmsApp/HashMapOuterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

abstract public class HashMapOuterHelper
{
  private static String  _id = "IDL:DhmsApp/HashMapOuter:1.0";

  public static void insert (org.omg.CORBA.Any a, DhmsApp.HashMapOuter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DhmsApp.HashMapOuter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "key",
            _tcOf_members0,
            null);
          _tcOf_members0 = DhmsApp.HashMapInnerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DhmsApp.innerHelper.id (), "inner", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DhmsApp.HashMapOuterHelper.id (), "HashMapOuter", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DhmsApp.HashMapOuter read (org.omg.CORBA.portable.InputStream istream)
  {
    DhmsApp.HashMapOuter value = new DhmsApp.HashMapOuter ();
    value.key = istream.read_string ();
    value.value = DhmsApp.innerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DhmsApp.HashMapOuter value)
  {
    ostream.write_string (value.key);
    DhmsApp.innerHelper.write (ostream, value.value);
  }

}
