package DhmsApp;


/**
* DhmsApp/HashMapInner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

public final class HashMapInner implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public int value = (int)0;

  public HashMapInner ()
  {
  } // ctor

  public HashMapInner (String _key, int _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class HashMapInner
