package DhmsApp;


/**
* DhmsApp/HashMapOuter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

public final class HashMapOuter implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public DhmsApp.HashMapInner value[] = null;

  public HashMapOuter ()
  {
  } // ctor

  public HashMapOuter (String _key, DhmsApp.HashMapInner[] _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class HashMapOuter
