package DhmsApp;


/**
* DhmsApp/innerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dhms.idl
* Sunday, October 27, 2019 5:46:38 o'clock PM EDT
*/

public final class innerHolder implements org.omg.CORBA.portable.Streamable
{
  public DhmsApp.HashMapInner value[] = null;

  public innerHolder ()
  {
  }

  public innerHolder (DhmsApp.HashMapInner[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DhmsApp.innerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DhmsApp.innerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DhmsApp.innerHelper.type ();
  }

}
